services:
  - type: web
    name: youtube-api-server
    env: go
    buildCommand: cd youtube-api-server && go mod download && go build -o main
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release

